[package]
name = "wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
fork = "0.1"
libc = "0.2"
signal-hook = "0.3"

log = "0.4"
pretty_env_logger = "0.4"
